apiVersion: v1
data:
  catalog.yml: |
    breakdown:
      type: xz_jssp.extras.datasets.metaxis.meta_parquet_dataset.MetaParquetDataSet
      table_fqn: syf.jssp.default.breakdown
    job_types:
      type: xz_jssp.extras.datasets.metaxis.meta_parquet_dataset.MetaParquetDataSet
      table_fqn: syf.jssp.default.job_types
    jobs:
      type: xz_jssp.extras.datasets.metaxis.meta_parquet_dataset.MetaParquetDataSet
      table_fqn: syf.jssp.default.jobs
    machines:
      type: xz_jssp.extras.datasets.metaxis.meta_parquet_dataset.MetaParquetDataSet
      table_fqn: syf.jssp.default.machines
    model_input:
      type: xz_jssp.extras.datasets.metaxis.meta_parquet_dataset.MetaParquetDataSet
      table_fqn: syf.jssp.default.{{ .Values.model_input }}
      table_meta:
        columns:
          - dataType: STRING
            name: data
        name: {{ .Values.model_input }}
        table_type: External
    cheduled:
      type: xz_jssp.extras.datasets.metaxis.meta_parquet_dataset.MetaParquetDataSet
      table_fqn: syf.jssp.default.{{ .Values.scheduled }}
      table_meta:
        columns:
          - dataType: STRING
            name: machine
          - dataType: STRING
            name: job
          - dataType: INT
            name: time
        name: {{ .Values.scheduled }}
        table_type: External
kind: ConfigMap
metadata:
  name: hackathon-catalog
